name: enladder_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  vocsy_epub_viewer: ^3.0.0
  http: ^1.2.2
  flutter_epub_viewer: 
    path: './lib/epub_viewer'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
